name: notario
description: Motor de disciplina para gestão de tempo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Google Sign-In
  google_sign_in: ^6.3.0

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
