// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbqYFWEEM6Ehd2w3CnrNVPLDCzkvUp9I',
    appId: '1:525067357557:android:3ff1c5a390dbc370b4173c',
    messagingSenderId: '525067357557',
    projectId: 'notario-6961f',
    storageBucket: 'notario-6961f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGIb7yKSTYww4fcl7QK8D1AEDjnIoQ_vw',
    appId: '1:525067357557:ios:d0efe4dc9d0fa0a8b4173c',
    messagingSenderId: '525067357557',
    projectId: 'notario-6961f',
    storageBucket: 'notario-6961f.firebasestorage.app',
    iosBundleId: 'com.example.notario',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_RyNjzmRZQDvuvaRW1fUTlcu6-NSMIU',
    appId: '1:525067357557:web:6a08cf4a02dee9f3b4173c',
    messagingSenderId: '525067357557',
    projectId: 'notario-6961f',
    authDomain: 'notario-6961f.firebaseapp.com',
    storageBucket: 'notario-6961f.firebasestorage.app',
    measurementId: 'G-83578D858F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGIb7yKSTYww4fcl7QK8D1AEDjnIoQ_vw',
    appId: '1:525067357557:ios:d0efe4dc9d0fa0a8b4173c',
    messagingSenderId: '525067357557',
    projectId: 'notario-6961f',
    storageBucket: 'notario-6961f.firebasestorage.app',
    iosBundleId: 'com.example.notario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp_RyNjzmRZQDvuvaRW1fUTlcu6-NSMIU',
    appId: '1:525067357557:web:95cffb8f1d081908b4173c',
    messagingSenderId: '525067357557',
    projectId: 'notario-6961f',
    authDomain: 'notario-6961f.firebaseapp.com',
    storageBucket: 'notario-6961f.firebasestorage.app',
    measurementId: 'G-8FTQ0KXH1R',
  );

}